use std::fmt;

/// A redacted error from the encrypted personal-state vault.
///
/// Variants deliberately carry no source strings: upstream crypto, parser, and I/O
/// errors may contain secret material or remote resource details. Callers can retain
/// this value in status snapshots and audit summaries without leaking those details.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum VaultError {
    InvalidDeviceId,
    InvalidDeviceIdentity,
    RandomnessUnavailable,
    InvalidAgeIdentity,
    InvalidAgeRecipient,
    InvalidSigningKey,
    WeakSigningKey,
    InvalidSignature,
    SignatureVerificationFailed,
    InvalidBase64,
    InvalidBase32,
    InvalidPairingCode,
    InvalidDatasetId,
    InvalidRandomLength,
    InvalidObjectKey,
    InvalidPrivateStore,
    InvalidMembership,
    MembershipAnchorMismatch,
    MembershipFork,
    RegistryMismatch,
    RevokedOrUnknownDevice,
    DeviceAlreadyExists,
    LastActiveDevice,
    ReplayDetected,
    RollbackDetected,
    SequenceGap,
    PairingExpired,
    PairingConsumed,
    RevisionConflict,
    RecoveryKitInvalid,
    MissingRecipients,
    TooManyRecipients,
    SerializationFailed,
    EncryptionFailed,
    DecryptionFailed,
    PayloadTooLarge,
    InvalidEncryptedObject,
    StorageFailed,
    StorageBusy,
    PreconditionFailed,
    ResourceLimitExceeded,
    KeyDerivationFailed,
    PairingProofFailed,
}

impl fmt::Display for VaultError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(match self {
            Self::InvalidDeviceId => "the device identity is invalid",
            Self::InvalidDeviceIdentity => "the device keys are invalid",
            Self::RandomnessUnavailable => "secure random generation is unavailable",
            Self::InvalidAgeIdentity => "the encryption identity is invalid",
            Self::InvalidAgeRecipient => "the encryption recipient is invalid",
            Self::InvalidSigningKey => "the signing key is invalid",
            Self::WeakSigningKey => "the signing key is not allowed",
            Self::InvalidSignature => "the signature encoding is invalid",
            Self::SignatureVerificationFailed => "the signature could not be verified",
            Self::InvalidBase64 => "the encoded value is invalid",
            Self::InvalidBase32 => "the pairing code encoding is invalid",
            Self::InvalidPairingCode => "the pairing code is invalid",
            Self::InvalidDatasetId => "the dataset identity is invalid",
            Self::InvalidRandomLength => "the random identifier length is invalid",
            Self::InvalidObjectKey => "the encrypted object key is invalid",
            Self::InvalidPrivateStore => "the private sync store is invalid",
            Self::InvalidMembership => "the device membership record is invalid",
            Self::MembershipAnchorMismatch => "the device membership anchor does not match",
            Self::MembershipFork => "the device membership history has conflicting branches",
            Self::RegistryMismatch => "the device registry does not match",
            Self::RevokedOrUnknownDevice => "the device is revoked or unknown",
            Self::DeviceAlreadyExists => "the device is already registered",
            Self::LastActiveDevice => "the last active device cannot be removed",
            Self::ReplayDetected => "a repeated protected operation was rejected",
            Self::RollbackDetected => "an older protected state was rejected",
            Self::SequenceGap => "the protected operation sequence has a gap",
            Self::PairingExpired => "the device pairing request expired",
            Self::PairingConsumed => "the device pairing request was already used",
            Self::RevisionConflict => "the local state changed before the operation completed",
            Self::RecoveryKitInvalid => "the recovery kit is invalid",
            Self::MissingRecipients => "no active recipient is available",
            Self::TooManyRecipients => "the active recipient limit was exceeded",
            Self::SerializationFailed => "the protected payload could not be encoded",
            Self::EncryptionFailed => "the protected payload could not be encrypted",
            Self::DecryptionFailed => "the protected payload could not be decrypted",
            Self::PayloadTooLarge => "the protected payload exceeds the size limit",
            Self::InvalidEncryptedObject => "the encrypted object is invalid",
            Self::StorageFailed => "the protected state could not be stored",
            Self::StorageBusy => "the protected state is in use",
            Self::PreconditionFailed => "the protected state changed before it was stored",
            Self::ResourceLimitExceeded => "the protected resource limit was exceeded",
            Self::KeyDerivationFailed => "the recovery signing key could not be derived",
            Self::PairingProofFailed => "the pairing proof could not be verified",
        })
    }
}

impl std::error::Error for VaultError {}
