use std::fmt::Write as _;
use std::path::{Path, PathBuf};

fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=assets/icons/ytm-tui.ico");
    // Embedded by the About card via `include_bytes!`; rebuild if the icon changes.
    println!("cargo:rerun-if-changed=assets/icons/ytm-tui.png");

    // The GUI frontend dist embeds only into `ytt-desktop` (feature = "desktop"); the lean
    // `ytt` TUI never sees it. Emitting the table here keeps it out of every other build.
    if std::env::var_os("CARGO_FEATURE_DESKTOP").is_some() {
        emit_gui_assets();
    }

    if std::env::var("CARGO_CFG_TARGET_OS").as_deref() != Ok("windows") {
        return;
    }

    let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").unwrap());
    let icon = manifest_dir
        .join("assets")
        .join("icons")
        .join("ytm-tui.ico")
        .display()
        .to_string()
        .replace('\\', "/");
    let rc = out_dir.join("ytm-tui.rc");
    std::fs::write(&rc, format!("1 ICON \"{icon}\"\n"))
        .expect("failed to write Windows resource script");

    embed_resource::compile(&rc, embed_resource::NONE)
        .manifest_required()
        .expect("failed to embed Windows icon resource");
}

/// Emit `OUT_DIR/gui_assets.rs`: a static table of the built frontend dist, stored **raw**
/// (no gzip — WKURLSchemeHandler bypasses content-decoding on macOS; docs/gui/04 §3.1).
/// A missing dist emits a stub page and the build still SUCCEEDS, so legacy feature-enabled
/// CI/clippy/test runs that never ran npm keep working — unless `YTM_TUI_REQUIRE_DIST=1`
/// (release/Nix/packaging), which makes a missing dist a hard error.
fn emit_gui_assets() {
    let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").unwrap());

    println!("cargo:rerun-if-env-changed=YTM_TUI_GUI_DIST");
    println!("cargo:rerun-if-env-changed=YTM_TUI_REQUIRE_DIST");

    // Explicit override (Nix passes a prebuilt dist) else the in-tree gui/dist.
    let dist = std::env::var_os("YTM_TUI_GUI_DIST")
        .map(PathBuf::from)
        .unwrap_or_else(|| manifest_dir.join("gui").join("dist"));
    println!("cargo:rerun-if-changed={}", dist.display());

    let require = std::env::var_os("YTM_TUI_REQUIRE_DIST").is_some_and(|v| v == "1");

    let mut files: Vec<(String, PathBuf)> = Vec::new();
    if dist.join("index.html").is_file() {
        collect_files(&dist, &dist, &mut files);
    } else if require {
        panic!(
            "YTM_TUI_REQUIRE_DIST=1 but no built frontend at {}.\n\
             Run `npm ci && npm run build` in gui/ (or set YTM_TUI_GUI_DIST to a prebuilt dist).",
            dist.display()
        );
    }

    let mut src = String::new();
    src.push_str("// @generated by build.rs — embedded frontend dist (raw bytes). Do not edit.\n");

    if files.is_empty() {
        // Stub: the build succeeds; the handler serves this notice at `ytm://app/index.html`.
        let stub = out_dir.join("stub_index.html");
        std::fs::write(&stub, STUB_INDEX_HTML).expect("write stub index");
        println!("cargo:rerun-if-changed={}", stub.display());
        src.push_str("pub const DIST_EMBEDDED: bool = false;\n");
        src.push_str("pub static ASSETS: &[(&str, &[u8], &str)] = &[\n");
        let _ = writeln!(
            src,
            "    (\"index.html\", include_bytes!({:?}), \"text/html; charset=utf-8\"),",
            stub.to_str().unwrap()
        );
        src.push_str("];\n");
    } else {
        files.sort();
        src.push_str("pub const DIST_EMBEDDED: bool = true;\n");
        src.push_str("pub static ASSETS: &[(&str, &[u8], &str)] = &[\n");
        for (rel, abs) in &files {
            println!("cargo:rerun-if-changed={}", abs.display());
            let _ = writeln!(
                src,
                "    ({:?}, include_bytes!({:?}), {:?}),",
                rel,
                abs.to_str().unwrap(),
                content_type_for(rel)
            );
        }
        src.push_str("];\n");
    }

    std::fs::write(out_dir.join("gui_assets.rs"), src).expect("write gui_assets.rs");
}

/// Recursively collect files under `dir`, keying each by its URL-style relative path
/// (forward slashes) from `root`.
fn collect_files(root: &Path, dir: &Path, out: &mut Vec<(String, PathBuf)>) {
    let Ok(entries) = std::fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect_files(root, &path, out);
        } else if let Ok(rel) = path.strip_prefix(root) {
            let key = rel
                .components()
                .map(|c| c.as_os_str().to_string_lossy())
                .collect::<Vec<_>>()
                .join("/");
            out.push((key, path.clone()));
        }
    }
}

fn content_type_for(path: &str) -> &'static str {
    match path.rsplit('.').next() {
        Some("html") => "text/html; charset=utf-8",
        Some("js" | "mjs") => "text/javascript; charset=utf-8",
        Some("css") => "text/css; charset=utf-8",
        Some("json" | "map") => "application/json",
        Some("svg") => "image/svg+xml",
        Some("png") => "image/png",
        Some("jpg" | "jpeg") => "image/jpeg",
        Some("webp") => "image/webp",
        Some("ico") => "image/x-icon",
        Some("woff2") => "font/woff2",
        Some("woff") => "font/woff",
        Some("ttf") => "font/ttf",
        Some("txt") => "text/plain; charset=utf-8",
        _ => "application/octet-stream",
    }
}

const STUB_INDEX_HTML: &str = "<!doctype html><html><head><meta charset=\"utf-8\">\
<title>YtmTui — dist missing</title>\
<style>body{font-family:system-ui,sans-serif;background:#1e1e2e;color:#cdd6f4;\
display:grid;place-items:center;height:100vh;margin:0}code{background:#313244;\
padding:2px 6px;border-radius:6px}</style></head><body><div>\
<h2>Frontend not built</h2>\
<p>Run <code>npm ci &amp;&amp; npm run build</code> in <code>gui/</code>, then rebuild.</p>\
</div></body></html>";
