//! Per-job durability: `<data dir>/transfers/<job-id>.json` snapshots the fetched track
//! list, every match outcome, and per-track write status — so a crash, rate-limit abort,
//! or dry-run picks up exactly where it left off (`ytt transfer resume <job-id>`). The
//! human-facing summary lands next to it as `<job-id>.report.json`.

use std::path::PathBuf;

use serde::{Deserialize, Serialize};

use super::matching::{MatchOutcome, TrackInput};
use super::{JobSpec, Stage};
use crate::util::safe_fs;

pub const CHECKPOINT_VERSION: u32 = 1;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Checkpoint {
    pub version: u32,
    pub job_id: String,
    pub spec: JobSpec,
    pub created_at: i64,
    pub updated_at: i64,
    pub stage: Stage,
    /// The destination created for this job (idempotent creation: recorded before the
    /// first write, so a resume never creates a second playlist).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub dest_id: Option<String>,
    /// Human name of the destination (report/UX).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub dest_name: Option<String>,
    /// Source items that were never matchable (Spotify local files / episodes / removed
    /// tracks), counted at fetch time for the report.
    #[serde(default)]
    pub skipped_local: u32,
    pub tracks: Vec<TrackEntry>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TrackEntry {
    pub input: TrackInput,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub outcome: Option<MatchOutcome>,
    #[serde(default)]
    pub written: bool,
}

impl Checkpoint {
    pub fn new(job_id: String, spec: JobSpec, tracks: Vec<TrackEntry>) -> Self {
        let now = crate::signals::unix_now();
        Self {
            version: CHECKPOINT_VERSION,
            job_id,
            spec,
            created_at: now,
            updated_at: now,
            stage: Stage::Fetching,
            dest_id: None,
            dest_name: None,
            skipped_local: 0,
            tracks,
        }
    }

    pub fn load(job_id: &str) -> anyhow::Result<Self> {
        use anyhow::{Context, bail};
        let path = checkpoint_path(job_id)
            .ok_or_else(|| anyhow::anyhow!("no data directory on this platform"))?;
        let text = safe_fs::read_to_string_no_symlink(&path)
            .with_context(|| format!("no checkpoint for job `{job_id}`"))?;
        let cp: Checkpoint = serde_json::from_str(&text).context("checkpoint is corrupt")?;
        if cp.version != CHECKPOINT_VERSION {
            bail!(
                "checkpoint version {} is not supported (expected {CHECKPOINT_VERSION})",
                cp.version
            );
        }
        Ok(cp)
    }

    pub fn save(&mut self) -> std::io::Result<()> {
        self.updated_at = crate::signals::unix_now();
        let Some(path) = checkpoint_path(&self.job_id) else {
            return Ok(());
        };
        safe_fs::write_private_atomic_json(&path, self)
    }

    /// Known jobs, newest first: `(job_id, stage, updated_at)`.
    pub fn list_all() -> Vec<(String, Stage, i64)> {
        let Some(dir) = transfers_dir() else {
            return Vec::new();
        };
        let Ok(entries) = std::fs::read_dir(dir) else {
            return Vec::new();
        };
        let mut out: Vec<(String, Stage, i64)> = entries
            .filter_map(|e| {
                let path = e.ok()?.path();
                let name = path.file_name()?.to_str()?;
                let job_id = name.strip_suffix(".json")?;
                if job_id.ends_with(".report") {
                    return None;
                }
                let text = safe_fs::read_to_string_no_symlink(&path).ok()?;
                let cp: Checkpoint = serde_json::from_str(&text).ok()?;
                Some((job_id.to_owned(), cp.stage, cp.updated_at))
            })
            .collect();
        out.sort_by_key(|(_, _, updated)| std::cmp::Reverse(*updated));
        out
    }
}

fn transfers_dir() -> Option<PathBuf> {
    directories::ProjectDirs::from("", "", "ytm-tui").map(|d| d.data_dir().join("transfers"))
}

/// Job ids are generated by [`super::new_job_id`] ([a-z0-9-]); reject anything else so a
/// hostile `--resume ../../x` can't escape the transfers directory.
fn safe_job_id(job_id: &str) -> Option<&str> {
    (!job_id.is_empty()
        && job_id
            .bytes()
            .all(|b| b.is_ascii_lowercase() || b.is_ascii_digit() || b == b'-'))
    .then_some(job_id)
}

pub fn checkpoint_path(job_id: &str) -> Option<PathBuf> {
    Some(transfers_dir()?.join(format!("{}.json", safe_job_id(job_id)?)))
}

pub fn report_path(job_id: &str) -> Option<PathBuf> {
    Some(transfers_dir()?.join(format!("{}.report.json", safe_job_id(job_id)?)))
}

/// The end-of-job summary (also serialized next to the checkpoint).
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct TransferReport {
    pub job_id: String,
    pub total: u32,
    pub matched: u32,
    pub written: u32,
    pub ambiguous: Vec<ReportRow>,
    pub not_found: Vec<ReportRow>,
    pub skipped_local: u32,
    pub duplicates_dropped: u32,
    pub elapsed_secs: u64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ReportRow {
    pub title: String,
    pub artists: String,
    /// Why it needs attention (top ambiguous candidates / "no match").
    pub note: String,
}

impl TransferReport {
    pub fn save(&self) -> std::io::Result<()> {
        let Some(path) = report_path(&self.job_id) else {
            return Ok(());
        };
        safe_fs::write_private_atomic_json(&path, self)
    }

    /// A terminal/status-line friendly summary.
    pub fn render_text(&self) -> String {
        let mut out = format!(
            "{}/{} matched, {} written, {} ambiguous, {} not found",
            self.matched,
            self.total,
            self.written,
            self.ambiguous.len(),
            self.not_found.len(),
        );
        if self.skipped_local > 0 {
            out.push_str(&format!(", {} local/episode skipped", self.skipped_local));
        }
        if self.duplicates_dropped > 0 {
            out.push_str(&format!(", {} duplicates dropped", self.duplicates_dropped));
        }
        out
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::transfer::{FileFormat, TransferDest, TransferSource};

    fn spec() -> JobSpec {
        JobSpec {
            source: TransferSource::SpotifyPlaylist {
                id: "37i9dQ".to_owned(),
            },
            dest: TransferDest::YtmNewPlaylist { name: None },
            dry_run: false,
            min_score: 0.80,
            take_best: false,
            rematch: false,
        }
    }

    fn entry(title: &str) -> TrackEntry {
        TrackEntry {
            input: TrackInput {
                title: title.to_owned(),
                artists: vec!["A".to_owned()],
                album: None,
                duration_secs: Some(200),
                isrc: None,
                source_key: format!("spotify:track:{title}"),
                known_video_id: None,
            },
            outcome: None,
            written: false,
        }
    }

    #[test]
    fn round_trips_with_mixed_outcomes() {
        let mut cp = Checkpoint::new(
            "sp2yt-test-0001".to_owned(),
            spec(),
            vec![entry("one"), entry("two")],
        );
        cp.tracks[0].outcome = Some(MatchOutcome::Matched {
            key: "vid1".to_owned(),
            score: 0.93,
            display: "A — one".to_owned(),
            title: Some("one".to_owned()),
            artist: Some("A".to_owned()),
            album: None,
            duration_secs: Some(200),
        });
        cp.tracks[0].written = true;
        cp.tracks[1].outcome = Some(MatchOutcome::NotFound);
        cp.stage = Stage::Writing;
        cp.dest_id = Some("PL123".to_owned());

        let json = serde_json::to_string(&cp).unwrap();
        let back: Checkpoint = serde_json::from_str(&json).unwrap();
        assert_eq!(back.tracks.len(), 2);
        assert!(back.tracks[0].written);
        assert!(matches!(
            back.tracks[0].outcome,
            Some(MatchOutcome::Matched { .. })
        ));
        assert!(!back.tracks[1].written);
        assert_eq!(back.dest_id.as_deref(), Some("PL123"));
        assert_eq!(back.stage, Stage::Writing);
        // FileFormat round-trip sanity for specs that carry it.
        let dest = TransferDest::File {
            path: std::path::PathBuf::from("/tmp/x.csv"),
            format: FileFormat::Csv,
        };
        let s = serde_json::to_string(&dest).unwrap();
        assert!(matches!(
            serde_json::from_str::<TransferDest>(&s).unwrap(),
            TransferDest::File {
                format: FileFormat::Csv,
                ..
            }
        ));
    }

    #[test]
    fn hostile_job_ids_are_rejected() {
        assert!(checkpoint_path("../escape").is_none());
        assert!(checkpoint_path("UPPER").is_none());
        assert!(checkpoint_path("").is_none());
        assert!(checkpoint_path("sp2yt-20260702-abcd").is_some());
    }

    #[test]
    fn report_renders_counts() {
        let report = TransferReport {
            job_id: "j".to_owned(),
            total: 10,
            matched: 8,
            written: 8,
            ambiguous: vec![ReportRow {
                title: "t".to_owned(),
                artists: "a".to_owned(),
                note: "n".to_owned(),
            }],
            not_found: Vec::new(),
            skipped_local: 1,
            duplicates_dropped: 0,
            elapsed_secs: 42,
        };
        let text = report.render_text();
        assert!(text.contains("8/10 matched"));
        assert!(text.contains("1 ambiguous"));
        assert!(text.contains("local/episode skipped"));
    }
}
