// Local GUI themes — frontend-owned skins that apply instantly with no core round-trip.
//
// Relationship to the core theme engine (docs/gui/06 §1–3): the 13 core presets stay
// core-resolved and the GUI embeds none of them; these local themes are a separate,
// deliberately small set of GUI-only skins. Precedence with the live core theme is settled
// (settings.theme-editor, stores/theme.svelte.ts): a chosen local skin layers on top of the
// pushed model and survives pushes until the user edits the core theme, which hands control
// back. Every palette must define all 34 roles — tests/wiring.test.ts enforces it.

export interface LocalTheme {
  id: string;
  name: string;
  /** One-line vibe, shown on the theme card. */
  tagline: string;
  scheme: 'light' | 'dark';
  /** role kebab-id → hex; must cover every id in lib/theme/roles.ts. */
  roles: Record<string, string>;
}

export const LOCAL_THEMES: LocalTheme[] = [
  {
    id: 'mocha',
    name: 'Mocha',
    tagline: 'the mini player’s Catppuccin — home base',
    scheme: 'dark',
    roles: {
      background: '#1e1e2e',
      'text-primary': '#cdd6f4',
      'text-muted': '#a6adc8',
      'text-subtle': '#7f849c',
      'text-inverse': '#1e1e2e',
      'border-primary': '#45475a',
      'border-focused': '#89b4fa',
      'border-muted': '#313244',
      accent: '#cba6f7',
      'accent-alt': '#f5c2e7',
      success: '#a6e3a1',
      warning: '#f9e2af',
      error: '#f38ba8',
      'selection-fg': '#1e1e2e',
      'selection-bg': '#cba6f7',
      'selection-inactive-fg': '#cdd6f4',
      'selection-inactive-bg': '#45475a',
      'gauge-filled': '#cba6f7',
      'gauge-empty': '#45475a',
      'player-control': '#cdd6f4',
      'player-label': '#a6adc8',
      'help-group': '#f9e2af',
      'help-key': '#89b4fa',
      'help-action': '#cdd6f4',
      'settings-group': '#f9e2af',
      'settings-label': '#a6adc8',
      'settings-value': '#cdd6f4',
      'settings-value-focused': '#89b4fa',
      'ai-user': '#89b4fa',
      'ai-assistant': '#a6e3a1',
      'ai-error': '#f38ba8',
      'ai-thinking': '#7f849c',
      'lyrics-current': '#cba6f7',
      'lyrics-dim': '#7f849c',
    },
  },
  {
    id: 'crimson-mono',
    name: 'Crimson Mono',
    tagline: 'black × red — sharp, modern, no noise',
    scheme: 'dark',
    roles: {
      background: '#0a0a0c',
      'text-primary': '#e8e6e3',
      'text-muted': '#9a9793',
      'text-subtle': '#615e5a',
      'text-inverse': '#0a0a0c',
      'border-primary': '#2c2c30',
      'border-focused': '#e5484d',
      'border-muted': '#1b1b1f',
      accent: '#e5484d',
      'accent-alt': '#ff6369',
      success: '#46a758',
      warning: '#ffb224',
      error: '#ff2e3f',
      'selection-fg': '#0a0a0c',
      'selection-bg': '#e5484d',
      'selection-inactive-fg': '#e8e6e3',
      'selection-inactive-bg': '#2c2c30',
      'gauge-filled': '#e5484d',
      'gauge-empty': '#26262a',
      'player-control': '#e8e6e3',
      'player-label': '#9a9793',
      'help-group': '#ff6369',
      'help-key': '#e5484d',
      'help-action': '#e8e6e3',
      'settings-group': '#ff6369',
      'settings-label': '#9a9793',
      'settings-value': '#e8e6e3',
      'settings-value-focused': '#ff6369',
      'ai-user': '#ff6369',
      'ai-assistant': '#c8c5c1',
      'ai-error': '#ff2e3f',
      'ai-thinking': '#615e5a',
      'lyrics-current': '#e5484d',
      'lyrics-dim': '#615e5a',
    },
  },
  {
    id: 'ember-wine',
    name: 'Ember Wine',
    tagline: 'orange × wine — warm, unhurried luxury',
    scheme: 'dark',
    roles: {
      background: '#241019',
      'text-primary': '#f3e3d3',
      'text-muted': '#c9a893',
      'text-subtle': '#8a6a5c',
      'text-inverse': '#2a0f12',
      'border-primary': '#55282f',
      'border-focused': '#e88b3a',
      'border-muted': '#3a1b22',
      accent: '#e88b3a',
      'accent-alt': '#d9a441',
      success: '#8fb573',
      warning: '#ddab55',
      error: '#d94f56',
      'selection-fg': '#2a0f12',
      'selection-bg': '#e88b3a',
      'selection-inactive-fg': '#f3e3d3',
      'selection-inactive-bg': '#55282f',
      'gauge-filled': '#e88b3a',
      'gauge-empty': '#472028',
      'player-control': '#f3e3d3',
      'player-label': '#c9a893',
      'help-group': '#d9a441',
      'help-key': '#e88b3a',
      'help-action': '#f3e3d3',
      'settings-group': '#d9a441',
      'settings-label': '#c9a893',
      'settings-value': '#f3e3d3',
      'settings-value-focused': '#e88b3a',
      'ai-user': '#e88b3a',
      'ai-assistant': '#d9a441',
      'ai-error': '#d94f56',
      'ai-thinking': '#8a6a5c',
      'lyrics-current': '#e88b3a',
      'lyrics-dim': '#8a6a5c',
    },
  },
  {
    id: 'ocean-glass',
    name: 'Ocean Glass',
    tagline: 'deep navy × cyan — cool and clear',
    scheme: 'dark',
    roles: {
      background: '#0b1420',
      'text-primary': '#d8e6f2',
      'text-muted': '#94aec4',
      'text-subtle': '#5a7186',
      'text-inverse': '#0b1420',
      'border-primary': '#27405a',
      'border-focused': '#4cc9f0',
      'border-muted': '#16273a',
      accent: '#4cc9f0',
      'accent-alt': '#80ffdb',
      success: '#6ede8a',
      warning: '#ffd166',
      error: '#ef476f',
      'selection-fg': '#0b1420',
      'selection-bg': '#4cc9f0',
      'selection-inactive-fg': '#d8e6f2',
      'selection-inactive-bg': '#27405a',
      'gauge-filled': '#4cc9f0',
      'gauge-empty': '#1d3145',
      'player-control': '#d8e6f2',
      'player-label': '#94aec4',
      'help-group': '#ffd166',
      'help-key': '#4cc9f0',
      'help-action': '#d8e6f2',
      'settings-group': '#ffd166',
      'settings-label': '#94aec4',
      'settings-value': '#d8e6f2',
      'settings-value-focused': '#4cc9f0',
      'ai-user': '#4cc9f0',
      'ai-assistant': '#80ffdb',
      'ai-error': '#ef476f',
      'ai-thinking': '#5a7186',
      'lyrics-current': '#4cc9f0',
      'lyrics-dim': '#5a7186',
    },
  },
  {
    id: 'daylight',
    name: 'Daylight',
    tagline: 'paper-light with a violet accent',
    scheme: 'light',
    roles: {
      background: '#faf7f2',
      'text-primary': '#2c2a33',
      'text-muted': '#5f5b6b',
      'text-subtle': '#918da0',
      'text-inverse': '#faf7f2',
      'border-primary': '#c9c4d4',
      'border-focused': '#7c5cff',
      'border-muted': '#e4e0ea',
      accent: '#7c5cff',
      'accent-alt': '#d6478f',
      success: '#2f9e63',
      warning: '#b07d00',
      error: '#d43d51',
      'selection-fg': '#faf7f2',
      'selection-bg': '#7c5cff',
      'selection-inactive-fg': '#2c2a33',
      'selection-inactive-bg': '#e4e0ea',
      'gauge-filled': '#7c5cff',
      'gauge-empty': '#dcd7e5',
      'player-control': '#2c2a33',
      'player-label': '#5f5b6b',
      'help-group': '#a06b00',
      'help-key': '#7c5cff',
      'help-action': '#2c2a33',
      'settings-group': '#a06b00',
      'settings-label': '#5f5b6b',
      'settings-value': '#2c2a33',
      'settings-value-focused': '#7c5cff',
      'ai-user': '#7c5cff',
      'ai-assistant': '#2f9e63',
      'ai-error': '#d43d51',
      'ai-thinking': '#918da0',
      'lyrics-current': '#7c5cff',
      'lyrics-dim': '#918da0',
    },
  },
];

export function localTheme(id: string): LocalTheme | null {
  return LOCAL_THEMES.find((t) => t.id === id) ?? null;
}

export const DEFAULT_LOCAL_THEME = LOCAL_THEMES[0];
